version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  github-cli: circleci/github-cli@1.0.5

jobs:
  create-release:
    docker:
      - image: "cimg/base:stable"

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - github-cli/setup
      - run:
          name: Create Release
          command: |
            gh release create $(git rev-parse --short HEAD) build_info

  build:
    docker:
      - image: cimg/clojure:1.11-browsers
        command: "/bin/bash"

    working_directory: ~/repo

    steps:
      - checkout
      - github-cli/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "core/deps.edn" }}-{{ checksum "dom/deps.edn" }}
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "core/yarn.lock" }}-{{ checksum "dom/yarn.lock" }}
            - v1-npm-deps-

      - run: cd core && yarn install --frozen-lockfile

      # removing gitconfig because it forces uix repo checkout via SSH
      # which fails when pulling in dependencies, default clone HTTPS works
      - run: rm ~/.gitconfig

      - run: cd core && scripts/test | tee ../build_info && curl -sSLo ../build_info_master https://github.com/pitch-io/uix/releases/latest/download/build_info

      - run: cd dom && scripts/test

      - when:
          condition:
            not:
              equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Comment on PR
                command: |
                  # Extract the PR number from the URL. https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
                  PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
                  gh pr comment $PR_NUMBER --body "$(./core/scripts/benchmark-ci)"

      - persist_to_workspace:
          root: .
          paths:
            - build_info

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "core/deps.edn" }}-{{ checksum "dom/deps.edn" }}

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-npm-deps-{{ checksum "core/yarn.lock" }}-{{ checksum "dom/yarn.lock" }}

workflows:
  version: 2
  test:
    jobs:
      - build
      - create-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
